version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: docker/php-fpm/Dockerfile
    container_name: php8-fpm
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php-fpm/conf/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - php8-network
  
  server:
    image: nginx:1.20.2-alpine
    container_name: php8-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/nginx/logs/nginx:/var/log/nginx
    networks:
      - php8-network

networks:
  php8-network:
    driver: bridge